#pragma once

#define WIFI_SSID_SECRET "YOUR_WIFI_SSID"
#define WIFI_PASSWORD_SECRET "YOUR_WIFI_PASSWORD"

#define MQTT_ENDPOINT "YOUR_AWS_IOT_ENDPOINT"

#define MQTT_ROOT_CA R"EOF(
-----BEGIN CERTIFICATE-----
YOUR_AWS_ROOT_CA
-----END CERTIFICATE-----
)EOF"

#define MQTT_DEVICE_CERT R"EOF(
-----BEGIN CERTIFICATE-----
YOUR_DEVICE_CERTIFICATE
-----END CERTIFICATE-----
)EOF"

#define MQTT_DEVICE_PRIVATE_KEY R"EOF(
-----BEGIN PRIVATE KEY-----
YOUR_DEVICE_PRIVATE_KEY
-----END PRIVATE KEY-----
)EOF"
