version = 0.1

[default.deploy.parameters]
stack_name = "demo-backend"
resolve_s3 = true
s3_prefix = "demo-backend"
region = "ap-southeast-5"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "ap-southeast-5"
